UI/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using UI.Areas.Admin.DTOS.CategoryDTO;

namespace UI.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class CategoryController : Controller
	{
		private readonly IHttpClientFactory	_http;
        public CategoryController(IHttpClientFactory http)
        {
            _http = http;
        }
		[HttpGet]
        public async Task<IActionResult> CategoryList()
		{
			var client=_http.CreateClient();
			var response = await client.GetAsync($"https://localhost:44391/api/Category/CategoryList");
			if (response.IsSuccessStatusCode)
			{
				var jsonData=await response.Content.ReadAsStringAsync();
				var values=JsonConvert.DeserializeObject<IEnumerable<CategoryListDTO>>(jsonData);
				return View(values);
			}
			else
			{
				return NotFound();
			}
			
		}
		[HttpGet]
		public IActionResult NewCategory()
		{
			NewCategoryDTO dto = new NewCategoryDTO();
			return View(dto);
		}
		[HttpPost]
		public async Task<IActionResult> NewCategory(CategoryListDTO dto)
		{
			var client=_http.CreateClient();		
			var jsondata=JsonConvert.SerializeObject(dto);
			StringContent content = new StringContent(jsondata,Encoding.UTF8,"application/json");
			var response = await client.PostAsync($"https://localhost:44391/api/Category/Create",content);
			if (response.IsSuccessStatusCode)
			{


				return RedirectToAction("CategoryList");
			}
			else
			{
				return NotFound();
			}	
		}
		
		public async Task<IActionResult> UpdateCategory(int Id)
		{
			var client = _http.CreateClient();
			var response = await client.GetAsync($"https://localhost:44391/api/Category/GetById/{Id}");
			if (response.IsSuccessStatusCode)
			{
				var jsonData = await response.Content.ReadAsStringAsync();
				var values = JsonConvert.DeserializeObject<UpdateCategoryDTO>(jsonData);			
			
				return View(values);
			}
			else
			{
				return NotFound();
			}
		}
		[HttpPost]
		public async Task<IActionResult> UpdateCategory(UpdateCategoryDTO dto)
		{
			var client = _http.CreateClient();
			var jsondata= JsonConvert.SerializeObject(dto);
			StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
			var response = await client.PutAsync($"https://localhost:44391/api/Category/Update/", content);
			if (response.IsSuccessStatusCode)
			{
				return RedirectToAction("CategoryList");
			}
			return NotFound();
		}


		public async Task<IActionResult> DeleteCategory(int Id)
		{
			var client = _http.CreateClient();
			var response = await client.DeleteAsync($"https://localhost:44391/api/Category/Delete/{Id}");
			if (response.IsSuccessStatusCode)
			{

				return RedirectToAction("CategoryList");
			}
			else
			{

				return NotFound();
			}
		}
	}
}

UI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace UI.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class DashboardController : Controller
	{
		
		public IActionResult Index()
		{
			return View();
		}
	}
}

UI/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using UI.Areas.Admin.DTOS.ProductDTO;

namespace UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IHttpClientFactory _http;
        public ProductController(IHttpClientFactory client)
        {

            _http = client;

        }
        [HttpGet]
        public async  Task<IActionResult> ProductList()
        {
            var client = _http.CreateClient();
            var response = await client.GetAsync($"https://localhost:44391/api/Product/List");
            if (response.IsSuccessStatusCode)
            {
                var jsonData = await response.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<IEnumerable<ProductListDTO>>(jsonData);
                return View(values);
            }
            return View();
          
        }
        [HttpGet]
        public async Task<IActionResult> ProductDetail(int Id)
        {
            var client= _http.CreateClient();
            var response = await client.GetAsync($"https://localhost:44391/api/Product/GetById/{Id}");
           
            if (response.IsSuccessStatusCode)
            {
                var jsonData=await response.Content.ReadAsStringAsync();
                var values=JsonConvert.DeserializeObject<GetProductDTO>(jsonData);
               
                return View(values);
            }
            else
            {

                return NotFound();
            }
          
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct()
        {
          AddProductDTO dto=new AddProductDTO();

            return View(dto);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProduct(AddProductDTO dto)
        {
            var client=_http.CreateClient();
            var jsondata = JsonConvert.SerializeObject(dto);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
            var response = await client.PostAsync($"https://localhost:44391/api/Product/Create", content);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("ProductList");
            }
            else
            {
              
                
                return View();
            } 
        }
        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int Id)
        {
			var client = _http.CreateClient();
			var response = await client.GetAsync($"https://localhost:44391/api/Product/GetById/{Id}");

			if (response.IsSuccessStatusCode)
			{
				var jsonData = await response.Content.ReadAsStringAsync();
				var values = JsonConvert.DeserializeObject<UpdateProductDTO>(jsonData);

				return View(values);
			}
            else
            {

                return NotFound();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProduct(UpdateProductDTO dto)
        {


            return View();
        }
        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int Id)
        {
            var client= _http.CreateClient();
            var response = await client.DeleteAsync($"https://localhost:44391/api/Product/Delete/{Id}");
            if (response.IsSuccessStatusCode)
            {
				return RedirectToAction("ProductList");
			}
            else
            {
                return NotFound();  
            }
          
        }
    }
}

UI/Controllers/HomeController.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
       

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            
            return View();
        }

    }
}

UI/Areas/Admin/Views/Category/CategoryList.cshtml
@model IEnumerable<UI.Areas.Admin.DTOS.CategoryDTO.CategoryListDTO>
@{
	ViewData["Title"] = "CategoryList";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	int num = 0;
}

<div class="wrapper">
	
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
			
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<div class="card-title">Yemək Kateqoriyaları</div>
								<div class="text-lg-right container">
									<a asp-action="NewCategory" style="color:white" class="btn btn-success">Yeni kateqoriya</a>
								</div>
							</div>
							<div class="card-body">
								<table class="table mt-3">
									<thead>
										<tr>
											<th scope="col">No</th>
											<th scope="col">Kateqoriyalar</th>
											<th scope="col">Status</th>
											<th scope="col">Əməliyyatlar</th>
										
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td>@(num=num+1)</td>
												<td>@item.Name</td>
												<td>@if (item.Status)
													{
														<span style="color:lawngreen">Açıq</span>
													}
													else
													{
														<span style="color:darkred">Bloklanıb</span>
													}
												</td>
												
												<td>
													<a asp-controller="Category" asp-action="UpdateCategory" asp-route-Id="@item.Id" style="color:white" class="btn btn-primary">Yenilə</a>
													<a asp-controller="Category" asp-action="DeleteCategory" asp-route-Id="@item.Id" style="color:white" class="btn btn-danger">Sil</a>
												</td>
											</tr>
										}
									
										
									</tbody>
								</table>
							</div>
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
		
	</div>
</div>

UI/Areas/Admin/Views/Category/NewCategory.cshtml
@model UI.Areas.Admin.DTOS.CategoryDTO.NewCategoryDTO
@{
    ViewData["Title"] = "Yeni kateqoriya";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="wrapper">
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
	      <form method="post">
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Yeni yemək kateqoriyası</div>
								</div>
								<div class="card-body">
									<div class="form-group">
										<label for="Name">Ad</label>
										<input type="text" class="form-control" asp-for="Name" id="categoryName" placeholder="Kateqoriya adını daxil edin...">

									</div>
								</div>
								<div class="card-action text-center">
									<button type="submit" class="btn btn-primary">Yarat</button>
									<a asp-action="CategoryList" class="btn btn-success">Geri</a>
								</div>
							</div>
						</div>
					
					</div>
	</form>
				
			</div>
		</div>
		
	</div>
</div>
@* <div class="col-md-6">
						<div class="card">
						<div class="card-header">
						<div class="card-title">Form Control Styles</div>
						</div>
						<div class="card-body">
						<div class="form-group">
						<label for="squareInput">Square Input</label>
						<input type="text" class="form-control input-square" id="squareInput" placeholder="Square Input">
						</div>
						<div class="form-group">
						<label for="squareSelect">Square Select</label>
						<select class="form-control input-square" id="squareSelect">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						</select>
						</div>
						<div class="form-group">
						<label for="pillInput">Pill Input</label>
						<input type="text" class="form-control input-pill" id="pillInput" placeholder="Pill Input">
						</div>
						<div class="form-group">
						<label for="pillSelect">Pill Select</label>
						<select class="form-control input-pill" id="pillSelect">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						</select>
						</div>
						<div class="form-group">
						<label for="solidInput">Solid Input</label>
						<input type="text" class="form-control input-solid" id="solidInput" placeholder="Solid Input">
						</div>
						<div class="form-group">
						<label for="solidSelect">Solid Select</label>
						<select class="form-control input-solid" id="solidSelect">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						</select>
						</div>
						</div>
						<div class="card-action">
						<button class="btn btn-success">Submit</button>
						<button class="btn btn-danger">Cancel</button>
						</div>
						</div>
						<div class="card">
						<div class="card-header">
						<div class="card-title">Form Control Styles</div>
						</div>
						<div class="card-body">
						<div class="form-group">
						<label for="largeInput">Large Input</label>
						<input type="text" class="form-control form-control-lg" id="largeInput" placeholder="Large Input">
						</div>
						<div class="form-group">
						<label for="largeInput">Default Input</label>
						<input type="text" class="form-control form-control" id="defaultInput" placeholder="Default Input">
						</div>
						<div class="form-group">
						<label for="smallInput">Small Input</label>
						<input type="text" class="form-control form-control-sm" id="smallInput" placeholder="Small Input">
						</div>
						<div class="form-group">
						<label for="largeSelect">Large Select</label>
						<select class="form-control form-control-lg" id="largeSelect">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						</select>
						</div>
						<div class="form-group">
						<label for="defaultSelect">Default Select</label>
						<select class="form-control form-control" id="defaultSelect">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						</select>
						</div>
						<div class="form-group">
						<label for="smallSelect">Small Select</label>
						<select class="form-control form-control-sm" id="smallSelect">
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						</select>
						</div>
						</div>
						<div class="card-action">
						<button class="btn btn-success">Submit</button>
						<button class="btn btn-danger">Cancel</button>
						</div>
						</div>
						</div> *@

UI/Areas/Admin/Views/Category/UpdateCategory.cshtml
@model UI.Areas.Admin.DTOS.CategoryDTO.UpdateCategoryDTO
@{
    ViewData["Title"] = "UpdateCategory";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="wrapper">
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<form method="post">
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Yeni yemək kateqoriyası</div>
								</div>
								<div class="card-body">
									<div class="form-group">
										<label for="Name">Ad</label>
										<input type="text" class="form-control" asp-for="Name" id="categoryName" placeholder="Kateqoriya adını daxil edin...">

									</div>
								</div>
								<div class="card-action text-center">
									<button type="submit" class="btn btn-primary">Yarat</button>
									<a asp-action="CategoryList" class="btn btn-success">Geri</a>
								</div>
							</div>
						</div>

					</div>
				</form>

			</div>
		</div>

	</div>
</div>

UI/Areas/Admin/Views/Product/AddProduct.cshtml
@model AddProductDTO
@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="wrapper">
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<form method="post">
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Yeni Məhsul</div>
								</div>
								<div class="card-body">
									<div class="form-group">
										<label for="squareSelect">Kateqoriya seçin</label>
										<select class="form-control input-square" id="squareSelect">
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
											<option>5</option>
										</select>
									</div>
									<div class="form-group">
										<label for="Name">Şəkil</label>
										<input type="file" class="form-control" asp-for="Photo" id="categoryName" placeholder="Kateqoriya adını daxil edin...">

									</div>
									<div class="form-group">
										<label for="Name">Açıqlama</label>
										<textarea type="text" class="form-control" asp-for="description" id="categoryName" placeholder="Məhsul haqqında məlumatları  daxil edin..." rows="5"></textarea>

									</div>
									
								
								
								<div class="card-action text-center">
									<button type="submit" class="btn btn-primary">Yarat</button>
									<a asp-action="ProductList" class="btn btn-success">Geri</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				</form>

			</div>
		</div>

	</div>
</div>

UI/Areas/Admin/Views/Product/ProductList.cshtml
@model IEnumerable<ProductListDTO>
@{
	ViewData["Title"] = "ProductList";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	int num = 0;
}

<div class="wrapper">

	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">

				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<div class="card-title">Yemək Kateqoriyaları</div>
								<div class="text-lg-right container">
									<a asp-action="AddProduct" style="color:white" class="btn btn-success">Yeni məhsul</a>
								</div>
							</div>
							<div class="card-body">
								<table class="table mt-3">
									<thead>
										<tr>
											<th scope="col">No</th>
											<th scope="col">Məhsul</th>
											<th scope="col">Kateqoriya</th>
											<th scope="col">Status</th>
											<th scope="col">Əməliyyatlar</th>

										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
											<tr>
												<td>@(num = num + 1)</td>
												<td>@item.Name</td>
												<td>@item.CategoryId</td>
												<td>
													@if (item.Status)
													{
														<span style="color:lawngreen">Açıq</span>
													}
													else
													{
														<span style="color:darkred">Bloklanıb</span>
													}
												</td>

												<td>
													<a asp-controller="Product" asp-action="UpdateProduct" asp-route-Id="@item.Id" style="color:white" class="btn btn-primary">Yenilə</a>
													<a asp-controller="Product" asp-action="DeleteProduct" asp-route-Id="@item.Id" style="color:white" class="btn btn-danger">Sil</a>
												</td>
											</tr>
										}


									</tbody>
								</table>
							</div>
						</div>

					</div>

				</div>
			</div>
		</div>

	</div>
</div>

UI/Areas/Admin/Views/Product/UpdateProduct.cshtml
@model UpdateProductDTO
@{
	ViewData["Title"] = "AddProduct";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="wrapper">
	<div class="main-panel">
		<div class="content">
			<div class="container-fluid">
				<form method="post">
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Məhsul məlumatlarını yenilə</div>
								</div>
								<div class="card-body">
									<div class="form-group">
										<label for="Name">Ad</label>
										<input type="text" class="form-control" asp-for="Name" id="categoryName" placeholder="Məhsul haqqında məlumatları  daxil edin..." />

									</div>
									<div class="form-group">
										<label for="squareSelect">Kateqoriya seçin</label>
										<select class="form-control input-square" id="squareSelect">
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
											<option>5</option>
										</select>
									</div>
									<div class="form-group">
										<label for="Name">Şəkil</label>
										<input type="file" class="form-control" asp-for="Photo" id="categoryName" placeholder="Kateqoriya adını daxil edin...">

									</div>

									<div class="form-group">
										<label for="Name">Açıqlama</label>
										<textarea type="text" class="form-control" asp-for="description" id="categoryName" placeholder="Məhsul haqqında məlumatları  daxil edin..." rows="5"></textarea>

									</div>



									<div class="card-action text-center">
										<button type="submit" class="btn btn-primary">Yarat</button>
										<a asp-action="ProductList" class="btn btn-success">Geri</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</form>

			</div>
		</div>

	</div>
</div>

UI/Areas/Admin/Views/Shared/Components/AdminLayoutFooterComponent/Default.cshtml
<div class="container-fluid">
	<nav class="pull-left">
		<ul class="nav">
			<li class="nav-item">
				<a class="nav-link" href="http://www.themekita.com">
					ThemeKita
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">
					Help
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="https://themewagon.com/license/#free-item">
					Licenses
				</a>
			</li>
		</ul>
	</nav>
	<div class="copyright ml-auto">
		2018, made with <i class="la la-heart heart text-danger"></i> by <a href="http://www.themekita.com">ThemeKita</a>
	</div>
</div>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/core/popper.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/core/bootstrap.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/chartist/chartist.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-mapael/jquery.mapael.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-mapael/maps/world_countries.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/chart-circle/circles.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/ready.min.js"></script>
<script src="~/Ready-Bootstrap-Dashboard-master/assets/js/demo.js"></script>
<script>
	$('#displayNotif').on('click', function () {
		var placementFrom = $('#notify_placement_from option:selected').val();
		var placementAlign = $('#notify_placement_align option:selected').val();
		var state = $('#notify_state option:selected').val();
		var style = $('#notify_style option:selected').val();
		var content = {};

		content.message = 'Turning standard Bootstrap alerts into "notify" like notifications';
		content.title = 'Bootstrap notify';
		if (style == "withicon") {
			content.icon = 'la la-bell';
		} else {
			content.icon = 'none';
		}
		content.url = 'index.html';
		content.target = '_blank';

		$.notify(content, {
			type: state,
			placement: {
				from: placementFrom,
				align: placementAlign
			},
			time: 1000,
		});
	});
</script>

UI/Areas/Admin/Views/Shared/Components/AdminLayoutHeaderComponent/Default.cshtml
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>İdarə Paneli</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
<link rel="stylesheet" href="~/Ready-Bootstrap-Dashboard-master/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
<link rel="stylesheet" href="~/Ready-Bootstrap-Dashboard-master/assets/css/ready.css">
<link rel="stylesheet" href="~/Ready-Bootstrap-Dashboard-master/assets/js/demo.js">

UI/Areas/Admin/Views/Shared/Components/AdminLayoutSideBarComponent/Default.cshtml
@model ItemCountsDTO
<div class="sidebar">
	<div class="scrollbar-inner sidebar-wrapper">
		<div class="user">
			<div class="photo">
				<img src="~/Ready-Bootstrap-Dashboard-master/assets/img/profile2.jpg">
			</div>
			<div class="info">
				<a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="true">
					<span>
				

					
						<span class="user-level">Administrator</span>
						<span class="caret"></span>
					</span>
				</a>
				<div class="clearfix"></div>

				<div class="collapse in" id="collapseExample" aria-expanded="true" style="">
					<ul class="nav">
						<li>
							<a  asp-controller="Account" asp-action="MyProfile">
								<span class="link-collapse">Profilim</span>
							</a>
						</li>
						<li>
							<a asp-controller="Account" asp-action="UpdateProfile" >
								<span class="link-collapse">Məlumatları yenilə</span>
							</a>
						</li>
						<li>
							<a asp-controller="Account" asp-action="Logout">
								<span class="link-collapse">Hesabdan çıxış</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<ul class="nav">
			<li class="nav-item active">
				<a asp-controller="Dashboard" asp-action="Index">
					<i class="la la-dashboard"></i>
					<p>Əsas Səhifə</p>
					<span class="badge badge-count"></span>
				</a>
			</li>
			<li class="nav-item">
				<a asp-controller="Category" asp-action="CategoryList">
					<i class="la la-table"></i>
					<p>Kateqoriyalar</p>
					<span class="badge badge-count">@Model.CategoryCount</span>
				</a>
			</li>
			<li class="nav-item">
				<a asp-controller="Product" asp-action="ProductList">
					<i class="la la-keyboard-o"></i>
					<p>Yeməklər</p>
					<span class="badge badge-count">@Model.ProductCount</span>
				</a>
			</li>
			<li class="nav-item">
				<a asp-controller="ContactUs" asp-action="UnReadMessageList">
					<i class="la la-th"></i>
					<p>Gələn mesajlar</p>
					<span class="badge badge-count">@Model.UnreadMessageCount</span>
				</a>
			</li>
			<li class="nav-item">
				<a asp-controller="Reservation" asp-action="ReservationList">
					<i class="la la-bell"></i>
					<p>Rezervasiyalar</p>
					<span class="badge badge-success">@Model.ReservationCount</span>
				</a>
			</li>
			<li class="nav-item">
				<a href="typography.html">
					<i class="la la-font"></i>
					<p>Haqqımızda</p>
					<span class="badge badge-danger">25</span>
				</a>
			</li>
			<li class="nav-item">
				<a href="icons.html">
					<i class="la la-fonticons"></i>
					<p>Təkliflər</p>
				</a>
			</li>
		
		</ul>
	</div>
</div>

UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>